In [1]:
#import sklearn
#import tensorflow as tf
#import keras

import pandas as pd
import numpy as np
#import scipy
import torch

In [2]:
#from sklearn.model_selection import train_test_split

In [3]:
train = pd.read_csv("data2/train.csv")
test = pd.read_csv("data2/test.csv")
sample = pd.read_csv("data2/sample_submission.csv")

In [4]:
train.head(5)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [5]:
train.drop("ID",inplace=True,axis=1)
id = test["ID"]
test.drop("ID",inplace=True,axis=1)
names = sample.columns.tolist()
sample.drop("ID",inplace=True,axis=1)

In [6]:
y_col = sample.columns.tolist()

y_train = train[y_col]
X_train = train.drop(y_col,axis=1)

print(X_train.shape)
print(y_train.shape)

(76020, 369)
(76020, 1)

In [7]:
X_train.head(10)

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000
1,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000
2,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000
3,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000
4,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
5,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,87975.750000
6,2,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94956.660000
7,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,251638.950000
8,2,45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,101962.020000
9,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,356463.060000

In [8]:
x = torch.Tensor(X_train.values)
y = torch.Tensor(y_train.values)

In [20]:
sum(y_train.iloc[:,0])/y_train.shape[0]

0.0395685345961589

In [24]:
device = torch.device('cpu')
N, D_in,  D_out = 76020, 369, 1
H = [500,1000,500,100]

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H[1]),
    torch.nn.LeakyReLU(),
    torch.nn.Linear(H[1], D_out)
    
)

l_r = 1e-9

for i in range(100):
    y_pred = torch.sigmoid(model(x))

    loss = torch.nn.functional.binary_cross_entropy(y_pred,y)
    print(loss)
    loss.backward()

    with torch.no_grad():
        for param in model.parameters():
            param -= l_r*param.grad
    model.zero_grad()

tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(5.3255, grad_fn=<BinaryCrossEntropyBackward0>)

KeyboardInterrupt:

In [15]:
X_test_2l = torch.Tensor(test.values)
y_pred_2l = model(X_test_2l)
#torch.nn.functional.softmax(y_pred_2l)
y_pred_2l = pd.DataFrame(y_pred_2l.detach()).astype("float")
y_pred_2l

               0
0       3.639604
1       4.096410
2       4.399087
3      17.188328
4       6.697162
...          ...
75813   3.642566
75814  13.407947
75815  15.371692
75816  10.690280
75817  10.791781

[75818 rows x 1 columns]

In [ ]:
y_pred_2l = pd.DataFrame(y_pred_2l.detach()).astype("float")

In [ ]:
from sklearn.preprocessing import quantile_transform
out_prob= quantile_transform(y_pred_2l)
out_prob = pd.DataFrame(out_prob)
out_prob

              0         1         2         3         4         5         6
0      0.149994  0.136169  0.159744  0.152661  0.110415  0.363860  0.112813
1      0.851671  0.738112  0.862576  0.759227  0.845507  0.740958  0.807648
2      0.944442  0.800568  0.953188  0.901234  0.939881  0.716384  0.909873
3      0.908666  0.678707  0.908315  0.876137  0.889081  0.523087  0.867507
4      0.812023  0.605388  0.811529  0.770819  0.792756  0.542310  0.767363
...         ...       ...       ...       ...       ...       ...       ...
12809  0.842156  0.660195  0.842339  0.781346  0.823586  0.645136  0.796988
12810  0.193460  0.127564  0.192611  0.253261  0.138762  0.093238  0.138257
12811  0.071502  0.963727  0.035715  0.611738  0.243976  0.934656  0.699697
12812  0.763713  0.636348  0.764448  0.643643  0.743231  0.705894  0.709681
12813  0.357584  0.891237  0.392550  0.146076  0.418539  0.915013  0.328113

[12814 rows x 7 columns]

In [ ]:


out_prob.columns = sample.columns
out_prob["id"] = id

In [ ]:
out_prob = out_prob[names]
out_prob.to_csv("output/2lnn_3.csv",index=False)